# Generated by Django 2.1.5 on 2019-02-20 05:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import monitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_image', models.ImageField(upload_to=monitor.models.dataset_directory_path)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_image', models.ImageField(upload_to='')),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, help_text='Student number must be this format 20YY-99999', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid student number (example:2019-123456)', regex='^20{1,2}[1-2][0-9]-[0-9]{6}')])),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=2)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to=monitor.models.user_directory_path)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEncoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_encoding', models.TextField()),
                ('student_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.Student')),
            ],
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='student_info',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Student'),
        ),
        migrations.AddField(
            model_name='datasets',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Student'),
        ),
    ]
