# Generated by Django 2.1.5 on 2019-02-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorlog',
            name='student_info',
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='student_number',
            field=models.CharField(default='Unknown', max_length=11),
        ),
    ]
