# Generated by Django 2.1.7 on 2019-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190223_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_webcam', models.CharField(max_length=255)),
                ('indentifier_interval', models.CharField(choices=[('5 Seconds', 5), ('10 Seconds', 10), ('15 Seconds', 15), ('30 Seconds', 30), ('1 Minute', 60)], default='5 Seconds', max_length=255)),
            ],
        ),
    ]
