# Generated by Django 2.1.7 on 2019-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_internalconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalconfiguration',
            name='indentifier_interval',
            field=models.CharField(choices=[(5, '5 Seconds'), (10, '10 Seconds'), (15, '15 Seconds'), (30, '30 Seconds'), (60, '1 Minute')], default='5 Seconds', max_length=255),
        ),
    ]
