# Generated by Django 2.1.7 on 2019-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190228_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalconfiguration',
            name='indentifier_interval',
            field=models.IntegerField(choices=[(5, '5 Seconds'), (10, '10 Seconds'), (15, '15 Seconds'), (30, '30 Seconds'), (60, '1 Minute')], default='5 Seconds'),
        ),
    ]
