# Generated by Django 2.1.7 on 2019-02-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20190228_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalconfiguration',
            old_name='indentifier_interval',
            new_name='identifier_interval',
        ),
    ]
